apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: registry.example.com/my-django-app
        ports:
        - containerPort: 8000
